apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclone
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: mysc
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: mypvc
