kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mypvc-autoexport
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: mysc-autoexport
